name: Test bird configuration
on:
  push:
  pull_request:
jobs:
  amd64:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Install bird2
        run: |
          sudo add-apt-repository ppa:cz.nic-labs/bird
          sudo apt-get update
          sudo apt-get install -y bird2
      - name: Test skeleton.conf syntax
        run: /usr/sbin/bird -c skeleton.conf -p

      - name: Generate aspa_invalids.conf
        run: ./make-bird-aspa aspa/example.json > aspa_invalids.conf
      - name: Test skeleton-aspa.conf syntax
        run: /usr/sbin/bird -c skeleton-aspa.conf -p
